### PR TITLE
Rename Guys.yaml to Guys.yml

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
The incorrect file name causes the test to not be found.

### CODE REVIEW

**Comment by jdkato** [comment]
Thanks for these PRs -- I appreciate the contributions!

That said, the [`styles/`](https://github.com/errata-ai/vale/tree/master/styles) directory has been largely deprecated (`Guys.yaml`, for example, isn't actually used anywhere) and is no longer accessible to users.

My plan for the next release of Vale (v1.0.0) is to

1. Disable all of Vale's current built-in rules by default [078e40b6495b7613fe0b1a836c56e2c8682a6678];
2. ship with complete styles for other linters (Vale's most requested feature), which will be found in the [`rule`](https://github.com/errata-ai/vale/tree/master/rule) package [61c476fc4105bf455acb810fd2c5653a6e5a3f97];
3. create and document a boilerplate repository (see [`vale-boilerplate`](https://github.com/errata-ai/vale-boilerplate)) that can used as a starting point for organizations to create and maintain their own styles; and
4. refactor any tests relying on the [`styles/`](https://github.com/errata-ai/vale/tree/master/styles) directory and remove it entirely (the styles are generally to incomplete to be useful anyway).

I think this will be make Vale more user-friendly (e.g., you'll get the functionality of many linters without having to install NPM, pip, etc.) and will make it clear that Vale is designed to be a non-opinionated linter (#42).

**Comment by ChrisChinchilla** [comment]
@jdkato OK, we might archive some of these vale versions of style guides into our own repo if that's OK with you? We wanted to create a suite of styles/rules of common style guides to show people (mostly writers) how they can codify their style guides and we found some of these template ones useful. And maybe you will find this list useful to refer people to if they get stuck with knowing how to create styles.

But I agree, know what to use when you first install Vale is confusing, and we were equally confused on multiple occasions :)

So we'll adjust what we've been working on (nearly ready) to reflect your changes and maintain our own little list of example vale configured style guides and look forward to your changes :)

OK with you? Chris

**Comment by jdkato** [comment]
Yes, that's fine with me. 

Let me know if there's anything I can do to help.

**Comment by ChrisChinchilla** [comment]
@jdkato Excellent. We'll take a copy now, and you can tell people to look at https://github.com/testthedocs/vale-styles if they want to find reference style guides, we will slowly add more examples over time.

I also look forward to watch the project for updates, and while I am not very good with go, we will try to contribute where we can :)

**Pull request closed without merging**
