### PR TITLE
chore: build linux_arm64

### LINKED ISSUE #448: Provide Linux/arm64 binary for use in Docker on m1 macs
Hi, it looks like the arm64 binary is only provided for darwin, having one for linux would be useful for Docker users on apple silicon to avoid running intel-based containers in emulation.

I guess this might be a trivial change since cross-compiling is trivial in go.

Once this is done it would additionally be great if the [docker image](https://hub.docker.com/r/jdkato/vale/tags) was published for [both platforms, amd64 and arm64](https://docs.docker.com/desktop/multi-arch/).

### PR DESCRIPTION
**Pull request by fwilhe**
This is useful for running in Docker on new macs.

Closes #448

Related to #411

### CODE REVIEW

**Comment by jdkato** [comment]
Thanks!

**Comment by fwilhe** [comment]
Perfect, thanks for the merge. Any chance we get a release soon where this binary will be part of?

**Comment by jdkato** [comment]
Yes, there will be a release later this week.

**Comment by fwilhe** [comment]
Very nice, thank you :)

**Pull request merged**
